##### linear algebra

When formalizing intuitive concepts, a common approach is to construct a
set of objects (symbols) and a set of rules to manipulate these objects. This
is known as an *algebra*.

In [1]:
import numpy as np

In [5]:
A = np.array(np.asmatrix('1 2; 3 4; 5 6'))

In [7]:
help(np.einsum)

Help on _ArrayFunctionDispatcher in module numpy:

einsum(*operands, out=None, optimize=False, **kwargs)
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
           casting='safe', optimize=False)

    Evaluates the Einstein summation convention on the operands.

    Using the Einstein summation convention, many common multi-dimensional,
    linear algebraic array operations can be represented in a simple fashion.
    In *implicit* mode `einsum` computes these values.

    In *explicit* mode, `einsum` provides further flexibility to compute
    other array operations that might not be considered classical Einstein
    summation operations, by disabling, or forcing summation over specified
    subscript labels.

    See the notes and examples for clarification.

    Parameters
    ----------
    subscripts : str
        Specifies the subscripts for summation as comma separated list of
        subscript labels. An implicit (classical Einstein summation)
        calculat

In [8]:
a = np.arange(25).reshape(5, 5,)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
np.einsum('ij->i', a)

array([ 10,  35,  60,  85, 110])

In [10]:
np.einsum('ii->i', a) 

array([ 0,  6, 12, 18, 24])

In [11]:
np.einsum('ij->j', a)

array([50, 55, 60, 65, 70])

In [12]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
b = np.arange(10).reshape(5, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

dot product of two matrices:
$c_ij = \sum_{l=1}^{n} a_{il} b_{lj}$

Commonly, the dot
product between
two vectors a,bis
denoted by a⊤b or$\langle a,b \rangle$.

In [24]:
np.dot(a, b)

array([[ 60,  70],
       [160, 195],
       [260, 320],
       [360, 445],
       [460, 570]])

Matrix multiplication is not defined as an element-wise operation
on matrix elements, i.e., $c_{ij} ≠ a_{ij} b_{ij}$ (even if the size of A,B was chosen appropriately). This kind of element-wise multiplication often appears
in programming languages when we multiply (multi-dimensional) arrays
with each other, and is called a *Hadamard product*.

identity matrix:$\R^{n \times n}$ is a matrix which has one on diagonal and 0 all over the place.

##### representation learning:
- autoencoder for example

##### deep learning.
The quintessential example of a deep learning model is the feedforward deep
network or multilayer perceptron (MLP). A multilayer perceptron is just a
mathematical function mapping some set of input values to output values. The
function is formed by composing many simpler functions. We can think of each
application of a different mathematical function as providing a new representation
of the input